build:
  nodes:
    php70:
      environment:
        php: 7.0
    php700:
      environment:
        php: 7.0.0
    analysis:
      project_setup:
        override: true
      tests:
        override: [php-scrutinizer-run]
  tests:
    override:
      -
        command: 'composer run tests'
        coverage:
          file: 'phpunit.clover'
          format: 'clover'

checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - './tests/'
